apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  annotations:
    version: 1.0.0
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
       - image: nginx:latest
         imagePullPolicy: IfNotPresent
         name: web
         volumeMounts:
         - mountPath: /etc/nginx/conf.d
           name: foo
           readOnly: true
         ports:
         - containerPort: 80
           protocol: TCP
      volumes:
      - name: foo
        configMap:
          name: nginx-conf
          #items:
          #- key: nginx.conf
          #  path: nginx.conf
